---

# coinwatch config
# Remote API: https://api.coinmarketcap.com/v1/ticker/?limit=0

# Config file description
# -----------------------
# trades:
#   # CURRENCY_ID is found by looking up the 'id' key from
#   # https://api.coinmarketcap.com/v1/ticker/?limit=0
#   CURRENCY_ID:  # <-- [array]       Each currency will hold a list of trades
#     - amount:   # <-- [decimal]     [1] How many coins for that currency were bought
#       invest:   # <-- [decimal]     [1] How much money was spent on all coins
#       price:    # <-- [decimal]     [1] Price for 1 coin when it was bought
#       cust1:    # <-- [string]      Custom column
#       cust2:    # <-- [string]      Custom column
#       cust3:    # <-- [string]      Custom column
#
# [1] IMPORTANT: Only always specify two of 'amount', 'invest' and 'price'.
#                The third value will always be calculated from the other two.
#
# [1] Trades can/must be configured in three different ways:
# Option-1
#     amount: how many coins bought
#     invest: how much money spent on all coins
# Option-2
#     amount: how many coins bought
#     price:  price for one coin
# Option-3
#     invest: how much money spent on all coins
#     price:  price for one coin

# Configure coinwatch
config:
  # Specify the default column to sort this table by or leave empty for unsorted.
  # Overwrite via -s <column>
  sort:
  # Specify the sort order (asc or desc)
  # Overwrite via -o desc
  order: asc
  # Configure what columns to display and in what order.
  # To see all available columns view help: $ coinwatch --help
  # Columns specified via command line (-r) take precedence
  #
  # There are also three other columns which are off by default: 'cust1', 'cust2' and 'cust3'.
  # Enable them here or via (-r).
  # Those three columns can be added to your trades in order to display custom information,
  # such as which market they were bought from or on what date they were bought.
  columns: symbol buyprice diffprice nowprice amount invest wealth profit percent
  # Define your custom columns here.
  # Set column headline and width.
  cust:
    cust1:
      headline: BUY DATE
      width: 01
    cust2:
      headline: MARKET
      width: 10
    cust3:
      headline: EXAMPLE
      width: 10
  # Specify your table border style
  # Available values: thin, thick and ascii
  # Use ascii if you want to further process the output of this application
  table: thin

trades:
  # bitcoin trades show all three different ways of specifying purchases.
  bitcoin:
    # Option-1: Invested 500.00$ and got 0.0425 coins
    - invest: 500.00
      amount: 0.0425
      cust1: 2016-04-30
      cust2: cryptopia
    # Option-2: bought at 10,010.50 and bought 0.5 coins
    - amount: 0.5
      price: 10010.50
      cust1: 2017-08-31
      cust2: cryptopia
    # Option-3: invested 500.00$ at 11,043.12 price/coin
    - invest: 500.00
      price: 11043.12
      cust1: 2017-12-05
      cust2: binance
  ethereum:
    - amount: 20
      price: 1070
      cust1: 2017-12-05
      cust2: binance
  iota:
    - amount: 100
      price: 2.15
      cust1: 2017-11-17
      cust2: cryptopia
  tron:
    - amount: 4000.234
      price: 0.0449101
      cust1: 2017-08-30
      cust2: binance
    - amount: 1821.15858466
      price: 0.0549101
      cust1: 2018-01-30
      cust2: binance
