---
###
### Sudo required
###
dist: trusty
sudo: required


###
### Set language
###
language: python


###
### Python Build Matrix
###
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"


###
###
###
install:
  # Install
  - pip install -r requirements.txt


###
### Run tests
###
script:
  # Show versions
  - ./bin/coinwatch --help
  - ./bin/coinwatch --version
